@hostname=localhost:44393
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6IjcyNDQ5ZmI2LTE0M2YtNDdjZi1hMDVjLWRhOGY0ZDNmMjQ5OSIsImV4cCI6MTc0NjQ5ODExMywiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.2siU3c5FGgBl8vhl8Nwur8c2yUtiBKmP0A6Vrb-IpSQ

###
GET https://{{hostname}}/api/ModuleItems
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
POST https://{{hostname}}/api/ModuleItems
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "name": "test 123",
  "parent_id": null,
}
###

###
GET https://{{hostname}}/api/ModuleItems/3
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
PUT https://{{hostname}}/api/ModuleItems/6
Content-Type: application/json
Authorization: Bearer {{token}} 
{
  "name": "Modules",
  "parent_id": 5,
  "parent_name": "Dashboard"
}
###

###
DELETE https://{{hostname}}/api/ModuleItems/1
Content-Type: application/json
Authorization: Bearer {{token}} 
###



