@hostname=localhost:44393
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6IjU2ZTk4ZDlkLTI4MzEtNDcyZC04YWM3LTMxZWQ0MzExOWUwNyIsImV4cCI6MTc0OTczODU4NSwiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.xwMTwwVk1slWf4NMYOkBII8G8xNQlq6ju0EHwSl_vBI


###
GET https://{{hostname}}/api/UserPermission/4
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
POST https://{{hostname}}/api/UserPermission
Content-Type: application/json
Authorization: Bearer {{token}} 
[
    {
        "id": 1,
        "name": "Dashboard",
        "user_id": null,
        "create": true,
        "read": true,
        "update": false,
        "delete": false
    },
    {
        "id": 2,
        "name": "Setup",
        "user_id": null,
        "create": true,
        "read": true,
        "update": false,
        "delete": false
    },
    {
        "id": 3,
        "name": "Users",
        "user_id": null,
        "create": false,
        "read": false,
        "update": false,
        "delete": false
    },
    {
        "id": 4,
        "name": "Permissions",
        "user_id": null,
        "create": false,
        "read": false,
        "update": false,
        "delete": false
    },
    {
        "id": 5,
        "name": "History",
        "user_id": null,
        "create": false,
        "read": false,
        "update": false,
        "delete": false
    }
]
###

