@hostname=localhost:44393
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6ImU1ZGFiMDdhLTQ2OTItNGU1ZC05NDFlLTY1NGU3OTJkZDViOCIsImV4cCI6MTc1MDU2NzEyMSwiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.qhXE9nqgDjCVHVyuq1A8sCRl_7nAt4cowg8utszlqDo


###
GET https://{{hostname}}/api/UserHistory?id=5&page=1
Content-Type: application/json
Authorization: Bearer {{token}} 
###

