@hostname=localhost:44393
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwidW5pcXVlX25hbWUiOiJkZXYiLCJqdGkiOiJkMzlmYTA4ZC02ODk0LTQwZWMtYjRiYi01YzNmMDg5Y2FmMTUiLCJleHAiOjE3NDgwOTY2ODksImlzcyI6IllvdXJBcGkiLCJhdWQiOiJZb3VyQ2xpZW50cyJ9.8sV9KoveOHgebI9Cbi2BK4erskmV0hUdPRNBB0nNfzE

###
GET https://{{hostname}}/api/User/
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
GET https://{{hostname}}/api/User/null
Content-Type: application/json
Authorization: Bearer {{token}} 
###