@hostname=localhost:44393
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6IjIyYmM0N2M1LTZmOTMtNDhhNS1hZGRjLWQwYmU3OWZjNTU2NiIsImV4cCI6MTc1MDQ3MTYzNSwiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.ZB0M6uMsecxcOnurVXLGRU7DDql_myL2WSpY63yTLew

###
GET https://{{hostname}}/api/User/search?user=dev
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
GET https://{{hostname}}/api/User/1
Content-Type: application/json
Authorization: Bearer {{token}} 
###


###
GET https://{{hostname}}/api/User?search=jm
Content-Type: application/json
Authorization: Bearer {{token}} 
###


###
PUT https://{{hostname}}/api/User/change-status/5?is_active=true
Content-Type: application/json
Authorization: Bearer {{token}} 
###