@hostname=localhost:44393
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwidW5pcXVlX25hbWUiOiJkZXYiLCJqdGkiOiIyODE5OTJkMS0xNWQxLTQ1MjAtYWQ3NS1hZTVkMWU2YjBlYTUiLCJleHAiOjE3NDgwNTY4NjQsImlzcyI6IllvdXJBcGkiLCJhdWQiOiJZb3VyQ2xpZW50cyJ9.rYhkhtt8goN3tFnu4-h9Ocp-TFlfme9go8vOVcK_DgU


###
GET https://{{hostname}}/api/UserHistory?id=5&page=1
Content-Type: application/json
Authorization: Bearer {{token}} 
###

