@hostname=localhost:44393
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6IjE4NWZiNTYxLWQ0MzMtNDgyMS05ZTIyLTA1ZDY3NzA0NmEzZiIsImV4cCI6MTc0NzE0NTAxMSwiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.GwC-K0eP3CZEy1tMd5a3BfPGfZLuEuyOnOdnqikCC7Y


###
GET https://{{hostname}}/api/UserPermission/45
Content-Type: application/json
Authorization: Bearer {{token}} 
###

