@hostname=localhost:44393
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6IjUwMjI1ZWFhLTdjZDctNDA3YS05MmIzLWFjYWE0YzJjN2NhYiIsImV4cCI6MTc0OTI3MTI5MiwiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.qj70dUAhZipQViS8NE6qs6b7nJ9xddzLbGiZaDGxfAA


###

GET https://{{hostname}}/api/Reports/CrashReport/Test
Content-Type: "application/json" 
Authorization: Bearer {{token}}

###

GET https://{{hostname}}/api/Reports/CrashReport?page=1
Content-Type: application/json
Authorization: Bearer {{token}} 

###

POST https://{{hostname}}/api/Reports/CrashReport
Content-Type: application/json
Authorization: Bearer {{token}} 
{
  "when": "2025-01-06",
  "where": "/dashboard",
  "what": "TESTING SAMPLE",
  "severity_level": "Medium",
  "created_by": 1
}

###



