@hostname=localhost:44393
@token = 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6ImQwZDcwMDIwLWYxZTgtNDBhZi04MzllLTIwZTdjYmI4NmUzMyIsImV4cCI6MTc0OTIyNzAxOCwiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.O6G3V6BuuBDZYjtfIAWqR3MIZqKCLwy4oZ9pRwcH7gI

GET https://{{hostname}}/api/Reports/CrashReport?page=1
Content-Type: application/json
Authorization: Bearer {{token}} 

###

POST https://{{hostname}}/api/Reports/CrashReport
Content-Type: application/json
Authorization: Bearer {{token}} 
{
  "when": "2025-01-06",
  "where": "/dashboard",
  "what": "TESTING SAMPLE",
  "severity_level": "Medium",
  "created_by": 1
}

###



