@hostname=localhost:44393
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6ImY0MDQ0NWQ5LTdiZmItNDllMC05YWE4LWEyMDAzNzc5MGMyMSIsImV4cCI6MTc1MDA4MzMzNywiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.SnMzVVeZ74MkRy7BPHVxu4OdLNobO80_OmVQlvpPo0E 


###

GET https://{{hostname}}/api/Reports/CrashReport/Test
Content-Type: "application/json" 
Authorization: Bearer {{token}}

###
GET https://{{hostname}}/api/Reports/CrashReport?page=1
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
GET https://{{hostname}}/api/Reports/CrashReport/metrics
Content-Type: application/json
Authorization: Bearer {{token}} 
###

###
GET https://{{hostname}}/api/Reports/CrashReport/69
Content-Type: application/json
Authorization: Bearer {{token}} 
###

POST https://{{hostname}}/api/Reports/CrashReport
Content-Type: application/json
Authorization: Bearer {{token}} 
{
  "when": "2025-01-06",
  "where": "/dashboard",
  "what": "TESTING SAMPLE",
  "severity_level": "Medium",
  "created_by": 1
}

###



