@hostname=localhost:44393
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImp0aSI6Ijg5NjEzZjMwLThmOGUtNDJmYi1iMWY2LTlkZTIzODYzMzNmNyIsImV4cCI6MTc0NDk1MTcwMywiaXNzIjoiWW91ckFwaSIsImF1ZCI6IllvdXJDbGllbnRzIn0.e8oQKcKyxxMiefkOjhvyb_4MdkAd-lWIAW9EmIoHzkc

GET https://{{hostname}}/api/auth
Content-Type: application/json

###

POST https://{{hostname}}/api/auth/register
Content-Type: application/json
{
  "username": "admin",
  "password": "password"
}

###

POST https://{{hostname}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET https://{{hostname}}/api/values
Authorization: Bearer {{token}} 
