@hostname=localhost:44393


GET https://{{hostname}}/api/auth
Content-Type: application/json

###

POST https://{{hostname}}/api/auth/register
Content-Type: application/json
{
  "username": "jmdelacruz",
  "password": "password"
}

###

POST https://{{hostname}}/api/auth/login
Content-Type: application/json

{
  "username": "jmdelacruz",
  "password": "password"
}

###
